# These are supported funding model platforms

ko_fi: auditnet
open_collective: auditnet
custom: ['https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=thepirat000%40hotmail.com&currency_code=USD&source=url']
